# See https://docs.docker.com/compose/compose-file/ for information about what
# commands you can use in this file.
#
# Note that you must use the `docker stack deploy` command, with any required
# command line flags, in order to actually get any replicas started. That
# command requires that a docker swarm is already running in order to function.

version: "3"
services:
  db:
    image: mongo:latest # Make sure your Docker image has this name.
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    # ports:
    #   - "4000:80"
    networks:
      backend_network:
        ipv4_address: 10.20.0.2

  backend:
    image: rest:latest # Make sure your Docker image has this name.
    stdin_open: true
    tty: true
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    ports:
      - "2000:8080"
    networks:
      - backend_network
      
networks:
  backend_network:
   ipam:
      driver: default
      config:
       - subnet: 10.20.0.0/16

