apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
spec:
  replicas: 1  # Adjust this based on how many replicas you want for each pod
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: backend-api
        image: backend-api
        ports:
        - containerPort: 8080  # Update this if your API listens on a different port

      - name: backend-db
        image: backend-db
        ports:
        - containerPort: 27017 #(Uncomment and update if your DB container needs to expose a port)

      - name: backend-dia
        image: backend-dia
        ports:
        - containerPort: 8082  # Update this as per your app's requirement

      - name: backend-tra
        image: backend-tra
        ports:
        - containerPort: 8081  # Update this as per your app's requirement
