apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  labels:
    name: {{ .Values.api.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port_guest }}
      nodePort: 31000
      name: api
  selector:
    name: {{ .Values.api.name }}