apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  labels:
    name: {{ .Values.database.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
      name: database
  selector:
    name: {{ .Values.database.name }}