apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    name: {{ .Values.frontend.name}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    name: {{ .Values.frontend.name}}


